name: System-Citybuild
main: Cb\System
api: 3.0.0
version: 1.2
author: bySuartix
commands:
        hub:
           description: "Teleport zur Hub"
        fw:
           description: "Farmwelt"
        setspawn:
           description: "Admin Command"
        citybuild:
           description: "Teleport zur Plotwelt"
